#!/bin/bash

: ${CONSUL_HOME:=/home/vagrant/consul}
: ${CONSUL_BIN:=/home/vagrant/consul/bin/consul}
: ${ADVETISE_IP:=$(hostname -I | cut -d' ' -f1)}
: ${NODE_NAME:=${ADVETISE_IP}}
: ${CONSUL_CONF_DIR:=${CONSUL_HOME}/conf}
: ${CONSUL_DATA_DIR:=${CONSUL_HOME}/data}
: ${CONSUL_LOG_DIR:=${CONSUL_HOME}/log}
: ${SERVER_OPTION:=}

mkdir -p ${CONSUL_CONF_DIR} ${CONSUL_DATA_DIR} ${CONSUL_LOG_DIR}

${CONSUL_BIN} agent \
	${SERVER_OPTION} \
	-advertise=${ADVETISE_IP} \
	-node=${NODE_NAME} \
	-config-dir=${CONSUL_CONF_DIR} \
	-data-dir=${CONSUL_DATA_DIR} \
	-bind=${ADVETISE_IP} \
	2>&1 | tee ${CONSUL_LOG_DIR}/${NODE_NAME}.log
